apiVersion: v1
kind: BuildConfig
metadata:
  name: poc-hello-ms-pipeline
spec:
  source:
    git:
      uri: "https://github.com/pablolazaro/poc-ms-hello"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: jenkins/Jenkinsfile